### ISSUE TITLE
Changing the URL?

### ISSUE THREAD

**Issue by zwartsy** [hfaran/slack-export-viewer#108]
Just can't work out how to change the URL from Localhost.
(New to python and dev work)
Thanks in advance.

**Comment by hfaran** [comment]
`slack-export-viewer --help`

You're looking for the `-I/--ip` option.

**Comment by zwartsy** [comment]
![image](https://user-images.githubusercontent.com/55067727/64496850-6594b180-d2e8-11e9-9357-c92026aa2484.png)
See above the error I receive.

**Comment by hfaran** [comment]
1) That's not how command-line arguments work. Use `-I 10.100.1.192`.
2) You didn't specify an archive, that's why you're getting the error; if you don't point to an archive, what do you expect to be displayed? Please read the README.

**Comment by zwartsy** [comment]
1. Thanks thats an easy fix
2. See below, it currently does have an archive and works with localhost:5000
![image](https://user-images.githubusercontent.com/55067727/64497012-cf618b00-d2e9-11e9-8051-1f2725959b8e.png)

**Comment by zwartsy** [comment]
Got there my self thanks mate.
See bellow, I edited the main.py for the slack archive as per bellow.

![image](https://user-images.githubusercontent.com/55067727/64578606-11103580-d3bf-11e9-8e76-a88e710c827f.png)
