### ISSUE TITLE
Unable to view output

### ISSUE THREAD

**Issue by circlecloudcommunications** [hfaran/slack-export-viewer#114]
I have set up everything as described but am unable to view any output when entering the external IP followed by port 5000 as the program indicates.

I tried installing Apache and I now get nothing on port 5000 but an Apache server page on port 80.

How can I get this app to display whenever I set the app up on my Digital Ocean droplet I get this:

root@slack-viewer:~# slack-export-viewer -z slack-export-ccc.zip
/tmp/_slackviewer/5e0d45a590fe4584213a2232c0b8c1b4a73c8494 already exists
 * Serving Flask app "slackviewer.app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://localhost:5000/ (Press CTRL+C to quit)

Is this normal?

**Comment by hfaran** [comment]
You need to use the `-I` option as per the documentation: https://github.com/hfaran/slack-export-viewer#installation
If you don't, by default it is only served on localhost.
