### ISSUE TITLE
setup error: about GBK

### ISSUE THREAD

**Issue by PLUSOROCHI** [hfaran/slack-export-viewer#123]
//I have corrected the error in setup.py by adding encoding='UTF-8'  please update it
def read(filename):
    """Read and return `filename` in root dir of project and return string"""
    here = os.path.abspath(os.path.dirname(__file__))
    return codecs.open(os.path.join(here, filename), 'r',encoding='UTF-8').read()

**Comment by hfaran** [comment]
Done: https://github.com/hfaran/slack-export-viewer/commit/f2d6abf773857660a9f6f2f1ee6cb452fc92ad9d
