### ISSUE TITLE
Allow HTML export (useful when migrating to Teams)

### ISSUE THREAD

**Issue by IndianTinker** [hfaran/slack-export-viewer#127]
Hello, Thanks a lot for the tool. It is absolutely magic.
I realize that it dynamically generates a page. Is it possible to somehow get a HTML page output that can be used to import things in Teams?

Or is there a directory that already has it?

Thanks :)

**Comment by hfaran** [comment]
Try this: https://github.com/hfaran/slack2html
If you have a problem with that tool, feel free to open an issue in that repo.
