### ISSUE TITLE
'slack-export-viewer' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by saswat-pandey** [hfaran/slack-export-viewer#137]
I am a beginner in python. But I saw this was a very highly rated package. I did the necessary steps, but ran into the issue where when I wrote "slack-export-viewer --help" I got the message as:

'slack-export-viewer' is not recognized as an internal or external command, operable program or batch file.

Could you please guide me as to how I can use this.
![py](https://user-images.githubusercontent.com/34863078/95597073-30dbb800-0a1c-11eb-804d-d0fc8d46b134.PNG)

**Comment by hfaran** [comment]
This is an issue with your environment setup, not with the tool. I can't help you with your Python install.
