### ISSUE TITLE
Cannot Install

### ISSUE THREAD

**Issue by williamsantoso93** [hfaran/slack-export-viewer#141]
Has anyone get this problem?
I have install using pip install slack-export-viewer

<img width="548" alt="Screen Shot 2021-04-01 at 11 35 07" src="https://user-images.githubusercontent.com/49981969/113243999-51574180-92de-11eb-932c-a57247068137.png">

Thanks

**Comment by cstuder** [comment]
Try

```bash
pipx install slack-export-viewer
python3 -m pipx ensurepath --force
```
