### ISSUE TITLE
How to make the answers be next to the channel message

### ISSUE THREAD

**Issue by GABuryan** [hfaran/slack-export-viewer#147]
Thanks for good work.
I'm downloading messages from the channel. 1 date -1 json-file. Viewer excelent work. But often replies to messages appear after a few days. And it's just that with sequential output, it's not clear which message they refer to. How can this problem be solved? In json file same key "thread_ts".  is it possible to somehow use this when unloading. Or is the strategy of unloading channel messages by day incorrect?

**Comment by devianvii** [comment]
The problem is sorting replies messages in the viewer after refactoring.
There is a very rough fix here (but it works for me): https://github.com/devianvii/slack-export-viewer

**Comment by GABuryan** [comment]
thanks, I'll try and write about the result

**Comment by GABuryan** [comment]
in this viewer I get this error - "  File "D:\sl_pr\venv2\lib\site-packages\slackviewer\reader.py", line 226, in _build_threads
    for reply in message._message['replies']:
KeyError: 'replies'"

Apparently we need a different format for uploading.

**Comment by GABuryan** [comment]
I downloading channels with project https://github.com/chr1spy1/slack-export

**Comment by GABuryan** [comment]
> The problem is sorting replies messages in the viewer after refactoring. There is a very rough fix here (but it works for me): https://github.com/devianvii/slack-export-viewer

Спасибо, бро. Твой экспорт и вьювер реально лучшие. Успехов.

**Comment by hfaran** [comment]
> The problem is sorting replies messages in the viewer after refactoring. There is a very rough fix here (but it works for me): https://github.com/devianvii/slack-export-viewer

@devianvii I thought I had merged your PR, but turns out I hadn't. Just merged it now, thanks for you fix. I'll make a release later, perhaps.
