### ISSUE TITLE
Access to local Host Denied

### ISSUE THREAD

**Issue by andymorse** [hfaran/slack-export-viewer#169]
Hey love your app, been using it on and off for a year or so and went to use it today and got Access to Local Host Denied on Mac and on Windows got Internal Server Error. Little lost, any issues you know about? Please let me know what time of logs I can send you to help.

**Comment by hfaran** [comment]
A good start would be specific details of the exact exceptions you're seeing (screenshots, logs, as many details as you can provide)

**Comment by hfaran** [comment]
Closing assuming the solution provided by @hclementeTera above is sufficient
