### ISSUE TITLE
"This site can't be reached"

### ISSUE THREAD

**Issue by thundergolfer** [hfaran/slack-export-viewer#19]
pip install worked correctly and command line indicates server is running:

`running on http://0.0.0.0:500/ (Press CTRL+C to quit)`

However when the browser tab opens you get a "This site can't be reached error".

**Comment by hfaran** [comment]
Are you on Windows? If so, try `localhost` instead of `0.0.0.0`

**Comment by hfaran** [comment]
Yeah, I'm going to guess that's the case; I'll make the default host `localhost` to be more Windows-friendly. Serving on all interfaces is probably a bad idea by default anyways.

**Comment by thundergolfer** [comment]
Thanks! That fixed it, going to locahost:5000

**Comment by hfaran** [comment]
I've got `0.1.3` ready to push to PyPI but it seems like PyPI is down right now... whenever it comes back up I'll push it. :P

**Comment by hfaran** [comment]
PyPI was finally behaving today so the push has been fixed.

**Comment by ottominggu** [comment]
pip install worked correctly and command line indicates server is running:

running on http://localhost:5000/ 

However when the browser tab opens you get a "This site can't be reached error".

**Comment by ottominggu** [comment]
Im using windows 7 and have install xamp, mysql on my pc can you help me

**Comment by hfaran** [comment]
@ottominggu Are you sure you're using the latest version? `pip install slack-export-viewer -U` to make sure.

The latest version is working perfectly fine for me on Windows 10.

**Comment by ottominggu** [comment]
pip install slack-export-viewer -U
Requirement already up-to-date: slack-export-viewer in c:\python27\lib\site-packages
Requirement already up-to-date: flask in c:\python27\lib\site-packages (from slack-export-viewer)
Requirement already up-to-date: click in c:\python27\lib\site-packages (from slack-export-viewer)
Requirement already up-to-date: markdown2 in c:\python27\lib\site-packages (from slack-export-viewer)
Requirement already up-to-date: emoji in c:\python27\lib\site-packages (from slack-export-viewer)
Requirement already up-to-date: itsdangerous>=0.21 in c:\python27\lib\site-packages (from flask->slack-export-viewer)
Requirement already up-to-date: Werkzeug>=0.7 in c:\python27\lib\site-packages (from flask->slack-export-viewer)
Requirement already up-to-date: Jinja2>=2.4 in c:\python27\lib\site-packages (from flask->slack-export-viewer)
Requirement already up-to-date: MarkupSafe in c:\python27\lib\site-packages (from Jinja2>=2.4->flask->slack-export-viewer)

**Comment by ottominggu** [comment]
the result still same whats is wrong with my setup cause i already follow all step

**Comment by hfaran** [comment]
Opened #22 to follow up with your issue

**Comment by RiyaBasale** [comment]
Hello i am facing the same problem with flask, when i use the local host as u recommended i am getting 404 Not Found error
