### ISSUE TITLE
No such file or directory in tmp/_slackviewer

### ISSUE THREAD

**Issue by TFranke1** [hfaran/slack-export-viewer#30]
I get an error upon processing the zip file. I am running OS X El Capitan. (I am very new to programing so I might be doing something wrong.)

10:~ TFranke$ slack-export-viewer -z /Users/TFranke/Downloads/Own-CL1.zip
/Users/TFranke/Downloads/Own-CL1.zip extracting to /tmp/_slackviewer/6775c84e42014a2a909e09769a2d07e86947f81a...
/Users/TFranke/Downloads/Own-CL1.zip extracted to /tmp/_slackviewer/6775c84e42014a2a909e09769a2d07e86947f81a.
Traceback (most recent call last):
  File "/Users/TFranke/.local/bin/slack-export-viewer", line 11, in <module>
    sys.exit(main())
  File "/Users/TFranke/.local/venvs/slack-export-viewer/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/TFranke/.local/venvs/slack-export-viewer/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/TFranke/.local/venvs/slack-export-viewer/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/TFranke/.local/venvs/slack-export-viewer/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/TFranke/.local/venvs/slack-export-viewer/lib/python2.7/site-packages/slackviewer/main.py", line 60, in main
    configure_app(app, archive, debug)
  File "/Users/TFranke/.local/venvs/slack-export-viewer/lib/python2.7/site-packages/slackviewer/main.py", line 35, in configure_app
    user_data = get_users(path)
  File "/Users/TFranke/.local/venvs/slack-export-viewer/lib/python2.7/site-packages/slackviewer/archive.py", line 31, in get_users
    with open(os.path.join(path, "users.json")) as f:
IOError: [Errno 2] No such file or directory: '/tmp/_slackviewer/6775c84e42014a2a909e09769a2d07e86947f81a/users.json'
10:~ TFranke$ 

This is the zip file: 
[Own-CL1.zip](https://github.com/hfaran/slack-export-viewer/files/588065/Own-CL1.zip)

**Comment by hfaran** [comment]
How did you get this zip? The reason this doesn't work is because you have another folder **inside** the zip called Own-CL1 which has the files. The regular export from Slack doesn't have this.

**Comment by hfaran** [comment]
So in order to get this to work, the zip file must contain the files directly. There should be not be a folder in between. Does that make sense?

**Comment by TFranke1** [comment]
hfaran, my bad. Safari was decompressing the zip file automatically and I was re-zipping it. I disabled the safe opening option in Safari, and now works like a charm. Thank you!. I have one more  question: From what I see, only text gets downloaded from slack, not pictures. Do you know any solution that downloads both text and pictures? We are using Slack to gather Retail Point of Sale data. We add a picture to each post. We would like to file this pictures off line. We are able to download pictures automatically using odrive, but these pictures download with a file name like "IMG2016112102.JPG" while we would like the picture to have the title of the post. "Store X - Brazil - Store ID 345". Do you know of any app that can do this? Can you develop this kind of app for us?

(I have uploaded a picture to be more clear)
Thank you!
<img width="691" alt="slack_-_own-cl" src="https://cloud.githubusercontent.com/assets/23433993/20262898/08c15f60-aa43-11e6-82fa-afd6e428fff6.png">

**Comment by hfaran** [comment]
Right now, slack-export-viewer only works with what it can get from the archive. What does the screenshot you're showing me look like with slack-export-viewer right now? Do the photos just not show up?

**Comment by TFranke1** [comment]
Exactly, on the export they don't show (and judging from the zip size, which is about 1.5 Mb, I guess they just don't download from slack, else this zip size would be near to 1 Gb. I am attaching a comparison of Slack vs the export. 

<img width="1439" alt="comparison" src="https://cloud.githubusercontent.com/assets/23433993/20264079/85229146-aa48-11e6-9810-b89621cdc555.png">

**Comment by hfaran** [comment]
That looks right. There is probably a way to make this work using the [files API](https://api.slack.com/types/file), but I unfortunately don't have any free time to spend towards this right now. If you know any programmer friends, maybe ask them if they'd be interested in helping you implement this.
I'm happy to look at pull requests, but just don't have time to implement this on my own right now.
