### ISSUE TITLE
Installing on WebFaction

### ISSUE THREAD

**Issue by feesh** [hfaran/slack-export-viewer#31]
Hi there!

I'm trying to get this hosted on WebFaction so I can share the archive viewer with my team, but am running into the following problem. Is there a way I can fork the viewer to not use the local Python 2.6, if that's the problem?

```[apiq@web42 cmww]$ slack-export-viewer CMWW\ Slack\ export\ Nov\ 29\ 2016.zip 
Traceback (most recent call last):
  File "/home/apiq/bin/slack-export-viewer", line 7, in <module>
    from slackviewer.main import main
  File "/home/apiq/lib/python2.6/slackviewer/main.py", line 8, in <module>
    from slackviewer.archive import \
  File "/home/apiq/lib/python2.6/slackviewer/archive.py", line 32
    return {u["id"]: u for u in json.load(f)}
                         ^
SyntaxError: invalid syntax
```

**Comment by hfaran** [comment]
Python 2.6 is indeed problematic because it does not support dict comprehensions. I'm assuming you're using CentOS 7. Do you have Python 2.7 installed as well? What method did you use to install slack-export-viewer?

**Comment by feesh** [comment]
Python 2.7 is installed also, but I can't seem to get it to use that explicitly. 

... actually you're totally right, looking back at the install steps I took, I used 2.6 to install pip. Re-doing it with 2.7 it works. Thank you! :)
