### ISSUE TITLE
Download pictures

### ISSUE THREAD

**Issue by mario6097** [hfaran/slack-export-viewer#44]
Hi

As far as I see, slack-export-viewer does not create code to see pictures on the local page, it renders  only a link to the slack url of the picture, doesn't it? 
Indeed, it would be nice to have slack-export-viewer be able to download pictures in a local folder. 
Any chance to see a improved code (which is already indeed very useful, but could be even more useful)
Thanks Cheers
mario

**Comment by hfaran** [comment]
At this time, I unfortunately don't have time to implement this, but I absolutely welcome a PR from you if you're up to the challenge. :)

**Comment by hfaran** [comment]
Actually, this PR already added it I believe: https://github.com/hfaran/slack-export-viewer/pull/40 
But it looks like the original contributor has left it. If you want to fix the couple comments I left on it, I will gladly accept it.

**Comment by mario6097** [comment]
Hi hfaran,
nope, unfortunately I have not an idea how to do it. 
Indeed, there is even something basic about Slack and picture I do not get, see [here](https://stackoverflow.com/questions/46132852/how-do-i-download-images-form-slack-by-php-or-wget)
