### ISSUE TITLE
backquote string "`" is deleted in message.py

### ISSUE THREAD

**Issue by future731** [hfaran/slack-export-viewer#66]
I've noticed that inline backquote symbol in a comment like `something` is somehow deleted. I haven't found the reason yet.

**Comment by hfaran** [comment]
Is this still happening? Do you have any examples showing this? (Original message on slack, a screenshot of slack-export-viewer, and the generated HTML as well would be useful).

**Comment by future731** [comment]
I haven't noticed that backquote is displaced with <code> tag until I saw the raw html code. I'll close this issue.
