### ISSUE TITLE
Show emoji reactions to messages

### ISSUE THREAD

**Issue by future731** [hfaran/slack-export-viewer#68]
It's better to show emoji reactions on messages.

**Comment by tscritch** [comment]
@future731 Are you thinking about opening a pull request for these features?

**Comment by future731** [comment]
@tscritch
I've already fixed USLACKBOT issue in my local repository, so I'll send a pull request to that one and close the issue.
I'm now struggling with this emoji one because it seems that emoji url is missing in archive json files.
I don't think I'll create a pull request about the thread tracking one. Backquote one neither.

**Comment by lsmith77** [comment]
@future731 ping? :)

**Comment by future731** [comment]
@lsmith77 pong. I'm struggling with this issue because we have to login the webpage to match the emoji email address.
It's pretty easy to show bare text like ":+1: by John, Mark"just after the msg text.

**Comment by future731** [comment]
Sorry that I've accidentary closed this issue, and I reopened this.

**Comment by future731** [comment]
https://github.com/future731/slack-export-viewer/commit/667e74c3717cb5c4add8f521597c575f4dde9932

The link above is the easiest workaround, but there are several reasons I didn't make a pull request.
1. a bot can react with emoji, which makes hard to convert slack user id into slack username.
Furthermore, even if we ignore bot emoji reaction, using self._message.get("reactions", [])[0].get("users") will return only slack user ids. SlackFormatter class member function "find_user(self, message)" needs message object.
2. my workaround is sometimes ugly if the emoji text is long.
3. I'm not familier with css style format, so I didn't do anything about css.

It'll be good to have reaction property in class Message though.

**Comment by lsmith77** [comment]
indeed .. the user.py would need to be refactored to be able to handle user ids from reactions properly. 

I tried to improve the code a bit but likely do to being a total python n00b this code is just producing empty reaction div's

```
                {"usernames": [self._formatter.find_user(Message(self._formatter, {"user": user})).display_name for user in reaction.get("users")], "name": emoji.emojize(':'+reaction.get("name")+':', use_aliases=True)}
```

**Comment by lsmith77** [comment]
will look into creating a PR

**Comment by future731** [comment]
I think this issue is resolved thanks to @lsmith77
