### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe3' in position 2: ordinal not in range(128)`

### ISSUE THREAD

**Issue by georgebrindeiro** [hfaran/slack-export-viewer#81]
Hi! Thanks for creating this great tool!

I am currently able to load my Slack Workspace Export, however some channels lead to a 500 Internal Server Error. Investigating the messages output in the terminal, I frequently see messages like:

`UnicodeEncodeError: 'ascii' codec can't encode character u'\xe3' in position 2: ordinal not in range(128)`

What could that be?

Cheers,
George

**Comment by uavpal** [comment]
same here: UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 7: ordinal not in range(128)

mine seems related to an URL: result = "<a href=\"{url}\">{title}</a>".format(url=url, title=title)

probably similar to https://github.com/hfaran/slack-export-viewer/commit/ac4eafbd51d54c7f7379500441e38cd7f328c1bb
and it's just a missing `encoding="utf8"` somewhere.

Rgds
SoftIce

**Comment by uavpal** [comment]
I can get around it by adding
```
import sys
reload(sys)
sys.setdefaultencoding('utf8')
```

starting from line 7 in formatter.py.
Probably only required for Python 2.7.
