### ISSUE TITLE
Slackbot variable problem

### ISSUE THREAD

**Issue by cereal76** [hfaran/slack-export-viewer#82]
File "c:\users\username\appdata\local\programs\python\python37\lib\sitepackages\slackviewer\formatter.py", line 37, in find_user    "real_name": bot_name,
UnboundLocalError: local variable 'bot_name' referenced before assignment

**Comment by cereal76** [comment]
Figured it out. On line 33 add:

`  else:
                bot_name = None
                bot_url = None`

**Comment by uavpal** [comment]
had the same issue and your solution fixed it! thanks man!

**Comment by hfaran** [comment]
Resolved by #84 . Published v 0.8.1.
