### ISSUE TITLE
Uses up all the memory on the host and then fails

### ISSUE THREAD

**Issue by jakubgs** [hfaran/slack-export-viewer#83]
I tried using this but it just sucks up all the memory available and then fails. I don't see how this is usable.

**Comment by hfaran** [comment]
It's possible that the archive you're trying to load is too large and the tool fails trying to load and render everything in memory. Something #73 might help with if it gets implemented.

**Comment by hfaran** [comment]
Thanks @vweevers! I just merged a variant of this solution. @jakubgs let us know if that helps.
