### ISSUE TITLE
Wrong order of messages (descending) within the same day

### ISSUE THREAD

**Issue by tjanez** [hfaran/slack-export-viewer#88]
This is an excerpt from the original Slack client, where messages are ordered correctly (i.e. in ascending order):
![original-slack-correct-order-within-the-day](https://user-images.githubusercontent.com/2518544/50542323-38b9c780-0bbb-11e9-958f-0bcab0c8e04d.png)

This is the same excerpt as rendered by slack-export-viewer, where messages are in wrong order (within the same day):
![slack-export-viewer-wrong-order-within-the-day](https://user-images.githubusercontent.com/2518544/50542332-6272ee80-0bbb-11e9-906b-eb1eea4a8b0f.png)

**Comment by hfaran** [comment]
What version of slack-export-viewer were you using?

**Comment by tjanez** [comment]
> What version of slack-export-viewer were you using?

Version 0.8.2 installed from PyPI.

**Comment by barnstws** [comment]
Looks like you need to sort entries in each json file

**Comment by tjanez** [comment]
This has been fixed in #106.
